import { useEffect, useState } from "react";
import Layout from "../components/Layout";
import { getUsers } from "../services/userService";
import { getEmployeeReview } from "../services/aiService";

export default function EmployeeReviews() {
  const [users, setUsers] = useState([]);
  const [selectedUser, setSelectedUser] = useState(null);
  const [review, setReview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const u = await getUsers();
        setUsers(u.filter(user => user.role !== "admin")); // hide admins from reviews if preferred, or leave them. Actually let's just list all.
        // I will list all users. 
        setUsers(u);
      } catch (err) {
        console.error(err);
      }
    };
    fetchUsers();
  }, []);

  const handleGenerateReview = async (user) => {
    setSelectedUser(user);
    setReview(null);
    setError("");
    setLoading(true);

    try {
      const rev = await getEmployeeReview(user._id);
      setReview(rev);
    } catch (err) {
      console.error(err);
      setError("Failed to generate review. Detailed error: " + (err.response?.data?.error || err.message));
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout>
      <h1 className="text-3xl font-bold mb-6 text-white flex items-center gap-2">
        Employees
      </h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* User List */}
        <div className="bg-slate-800/80 border border-slate-700 p-6 rounded-xl shadow-lg lg:col-span-1 h-fit">
          <h2 className="font-semibold mb-4 text-white">Select Employee</h2>
          <div className="flex flex-col gap-2">
            {users.map(u => (
              <button
                key={u._id}
                onClick={() => handleGenerateReview(u)}
                className={`text-left px-4 py-3 rounded border transition-all ${
                  selectedUser?._id === u._id 
                  ? "bg-purple-900/40 border-purple-500 shadow-[0_0_15px_rgba(168,85,247,0.15)]" 
                  : "bg-slate-900/50 border-slate-700 hover:bg-slate-800 hover:border-slate-600"
                }`}
              >
                <div className="font-medium text-slate-100">{u.name}</div>
                <div className="text-xs text-slate-400">{u.email}</div>
                <div className="mt-2 text-xs">
                    <span className="bg-slate-700/50 px-2 py-0.5 rounded text-slate-300">{u.role}</span>
                </div>
              </button>
            ))}
            {users.length === 0 && <div className="text-sm text-slate-400">No users found.</div>}
          </div>
        </div>

        {/* Review Area */}
        <div className="bg-slate-800/80 border border-slate-700 p-6 rounded-xl shadow-lg lg:col-span-2 min-h-[500px]">
          {selectedUser ? (
            <div>
              <h2 className="font-semibold mb-1 text-white text-xl">Review: {selectedUser.name}</h2>
              <p className="text-slate-400 text-sm mb-6">Generated by AI based on task history.</p>

              {loading && (
                <div className="flex flex-col items-center justify-center py-20 text-purple-400 animate-pulse">
                  <span className="text-4xl mb-4">✨</span>
                  <p>Analyzing employee tasks and activity...</p>
                </div>
              )}

              {error && (
                <div className="bg-red-950/50 border border-red-500/50 text-red-200 p-4 rounded-lg">
                  {error}
                </div>
              )}

              {review && (
                <div className="bg-slate-900/60 border border-slate-700 rounded-lg p-6">
                  <div className="prose prose-invert prose-purple max-w-none text-slate-300 whitespace-pre-wrap leading-relaxed">
                    {review}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center h-full py-20 text-slate-500">
              <span className="text-4xl mb-2 opacity-50">✨</span>
              <p>Select an employee from the list to generate their review.</p>
            </div>
          )}
        </div>

      </div>
    </Layout>
  );
}
